# filepath: docker-compose.yml
version: '3'
services:
  backend:
    build: ./backend
    container_name: seirp-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - DEBUG=1
    command: ["sleep", "infinity"]
    #command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    # uvicorn main:app --host 0.0.0.0 --port 5001 --reload
  
  seirp-db:
    image: postgres:15.10-bookworm
    container_name: seirp-db
    volumes:
      - ./docker/seirp-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      
  frontend:
    build: ./frontend
    container_name: seirp-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    stdin_open: true