"""First migration

Revision ID: 966d7b748f4b
Revises: 
Create Date: 2025-03-02 19:43:55.655735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966d7b748f4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('street_number', sa.String(length=16), nullable=True),
    sa.Column('street_name', sa.String(length=64), nullable=True),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_line_1', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=21), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('actual_address', sa.Uuid(), nullable=True),
    sa.Column('actual_location', sa.Uuid(), nullable=True),
    sa.Column('normal_address', sa.Uuid(), nullable=True),
    sa.Column('normal_location', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'RESTING', 'AVAILABLE', name='resourcestatusenum'), nullable=False),
    sa.Column('responsible', sa.String(length=128), nullable=False),
    sa.Column('telephone', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actual_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['actual_location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['normal_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['normal_location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('emergencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emergency_type', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('emergency_status', sa.Enum('UNKNOWN', 'ACTIVE', 'INACTIVE', 'SOLVED', name='emergencystatusenum'), nullable=True),
    sa.Column('location_emergency', sa.Uuid(), nullable=True),
    sa.Column('address_emergency', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('location_resource', sa.Uuid(), nullable=True),
    sa.Column('address_resource', sa.Uuid(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('location_destination', sa.Uuid(), nullable=True),
    sa.Column('address_destination', sa.Uuid(), nullable=True),
    sa.Column('name_contact', sa.String(length=128), nullable=False),
    sa.Column('telephone_contact', sa.String(length=128), nullable=False),
    sa.Column('id_contact', sa.String(length=128), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['address_destination'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['address_emergency'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['address_resource'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['location_destination'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['location_emergency'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['location_resource'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencies_id'), 'emergencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergencies_id'), table_name='emergencies')
    op.drop_table('emergencies')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
